### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by oscarnava**
This is the first version of the fourth project for the Microverse training program.
It was developed by Oscar (aka. Monstruo) using basic html tags, and CSS styling.

### CODE REVIEW

**Comment by jofer86** [comment]
# Pull Request Under Review By Jorge F. (TSE)

**Comment by jofer86** [comment]
# Hello Monstruo!! :wave: :wave: . I'll be doing the review for your project today. Looking forward to see what you did!.

### First of all the site looks amazing, the proportions of the elements seem on point and the max-width is set properly. Now let's get a bit deeper into the review.


# Minimum Requirements Checklist

To consider the project 'complete' it must satisfy the following points:

### Project Specification Shortcut

#### Navbar

:warning: It should use a linear gradient as background color **Even though what you did with the coloring for the navbar is quite impressive and  achieves the visual result that is wanted, the goal for this project is to use a linear gradient as a background color, and from what I can see you used a png and svg files to achieve this effect, kindly apply a linear gradient to the navbar to keep things according to the guidelines for this project**

:heavy_check_mark: It should be made of nine different buttons with the Apple logo on the leftmost section and a search field on the rightmost section

##### Buttons

:heavy_check_mark:  It has buttons positioned either as *floats* or *display flex* **Inline-flex was used but achieves the same result so I don't see a reason to ask you for a change**

##### Search field

:heavy_check_mark: The search field should be an `<input>` HTML tag with the *focus* effect enabled

#### Main content links

:heavy_check_mark: There should be three links
:warning: Each link is an `<a>` HTML tag, with a `<div>` tag inside it. **I see you placed the anchors inside a `<div>` tag, let us do this part like it is said in the guidelines**
:warning: The `<div>` tag inside the `<a>` tag should use an image as background -- \[ \] The text on the original page is actually an image **Instead of going out of your way to make a png image with a text to match you can leave the text you have and just set a background image as transparent to achieve the same effect**

#### Footer

## According to the guidelines the footer starts right after the alpinist images, so those four links should be part of the footer, please do make that adjustment.

:heavy_check_mark:  It should be wrapped by `<footer>` tags
:warning: The top part is made of four `<a>` tags with `<div>` tags inside it **Please refer to my observation and make the necessary changes to the footer section**
:warning: The `<div>`s inside the `<a>` tags should use an image as a background **Just like in the previous section, now just make sure you set a background image to the `<div>` tags that are going to live inside the anchor tags**
:heavy_check_mark: The bottom part should include links like copyright, terms of use, and privacy policy

### As you can see Monstruo, some minor changes to be made, the work on the site was phenomenal, but the Microverse guidelines has some quirks about the requirements. Great Job, Oscar.

## Cheers, Jorge! :mexico: :mexico:

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Hi there @oscarnava 
You are doing a great job on this project. But before merging to master we need to make just a few changes to make it in line with Microverse Guidelines.

- Main content links (The 3 main sentences)

- [x] Each link is an a HTML tag, with a div tag inside it.

- [x]  The div tag inside the a tag should use an image as background. The text on the original page is actually an image. This approach is required by Microverse guidelines. There is no need to use img tag here. Only a tag and div.

- [x] Delete the text from the anchor tag. Use just the images.

- Footer

- [x]  The top part is made of four a tags with div tags inside it

- [x] The divs inside the a tags should use an image as a background. The same approach of the 3 main sentences.

Kindly submit for code review again after the changes.

**Review by Ispirett — APPROVED** [review]
Hey folks great work with this project with you changes. :1st_place_medal:  You can merge this project now! 

# branching 
Also important note for feature HTML projects use a feature branch instead of development you can give that branch descriptive name that describes the feature you are implementing.

**Pull request merged**
